<?php
namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\Response;

/**
 * Class BasicController
 * @package app\controllers
 *
 * @property string $ip
 * @property string $msg
 * @property string $error
 * @property int $error_type
 * @property mixed $data
 */

class BasicController extends Controller
{

    /**
     * IP remote
     *
     * @var
     */
    public $ip;

    /**
     * Сообщение об ошибке
     *
     * @var
     */
    public $msg;

    /**
     * Наличие ошибки
     *
     * @var
     */
    public $error;

    /**
     * Цифровой тип ошибки
     *
     * @var int
     */
    public $error_type = 0;

    /**
     * Данные к выдаче
     *
     * @var
     */
    public $data;


    public function init_ajax()
    {
        $this->error = 'yes';
        $this->msg = 'Ошибка. Не определён ни один параметр';
        Yii::$app->response->format = Response::FORMAT_JSON;
    }

    /**
     * Стандартная выдача сообщений
     *
     * @return array
     */
    public function out()
    {
        return ['error'=>$this->error, 'error_type'=>(!empty($this->error_type)) ? $this->error_type : '','msg'=>$this->msg, 'data'=> ($this->error=='no') ? $this->data : '' ];
    }

    /**
     * Базовая инициализация
     */

    public function init(){
        $this->ip = Yii::$app->request->userIP;
    }

    public function beforeAction($action)
    {
        $this->init();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}