<?php

namespace app\controllers;

use Yii;
use app\models\Quiz_input;

class InputController extends BasicController
{

    public function runAction($id, $params = [])
    {
        Yii::$app->controller->enableCsrfValidation = false;
        return parent::runAction($id, $params);
    }

    public function init()
    {
        $this->enableCsrfValidation = FALSE;
        $this->layout = FALSE;
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function actionQuiz()
    {
        $this->init_ajax();
        //$data = json_decode(file_get_contents('php://input'), true);

        $model = new Quiz_input();
        $model->date_add = self::getNowDateTime();
        $model->content = file_get_contents('php://input');
        $model->ip = $this->ip;
        if (!$model->save()) foreach ($model->getErrors() as $key => $value) {
            $this->error = 'no';
            $this->data = 'Error: ' . $key . ': ' . $value[0];
        }
        return $this->out();
    }

    public static function getNowDateTime()
    {
        $dateFile = new \DateTime();
        return $dateFile->format('Y-m-d H:i:s');
    }

    public static function getNowDate()
    {
        $dateFile = new \DateTime();
        return $dateFile->format('Y-m-d');
    }
}
